### ISSUE TITLE
Keep timer when leaving site

### ISSUE THREAD

**Issue by Sacus1** [KY246/jpdBlock#6] opened 2024-12-27 15:28 UTC
When a user spends points to access 20 minutes of a website and leaves the site after only 2 minutes, the remaining 18 minutes are lost. Could it be possible to implement a system that restores the unused time when the page is reopened? Additionally, having this remaining time-shared across tabs would be incredibly useful, particularly on websites where multiple tabs are frequently used.

I'm unsure about the feasibility of this idea, but I wanted to propose it for consideration.

**Comment by KY246** [comment] 2024-12-28 06:19
I guess the first idea will be easiest to do by subtracting a few seconds from the remaining time regularly instead of just setting a time for when the time will run out.

The second idea is already possible if you select the `use regex` button with the `/gi` option, and separate the urls with `|` like below:
`(nbcnews\.com|youtube\.com|bbc\.com)`
I will look into a more user-friendly method for doing this.

To Do:
- [x] Subtract remaining time incrementally
- [x] Support for multiple sites in blocklist

**Comment by KY246** [comment] 2024-12-30 08:37
Both issues have been fixed in version 2.1.

Looking back at your first comment, it looks like I may have misunderstood your second point, and you meant tabs of the same page instead of multiple sites on the same blocklist.

If that is the case, the extension already should have been sharing time between tabs of the same page, so if that wasn't happening for you, that was likely a bug, and I would appreciate it if you can send me your browser and OS info so I can try reproducing it.

Closing this issue for now.

**Closed as completed by KY246** 2024-12-30 08:37 UTC

**Comment by Sacus1** [comment] 2024-12-30 11:24
This issue seems to have been resolved, potentially due to the new time management changes. Alternatively, it may have been a misunderstanding on my part. Either way, the problem appears to be resolved.
